---
- name: Create an empty file locally
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create the file
      file:
        path: /home/ansible_proof
        state: touch
