---
##########################################################
# Host configuration                                     #
##########################################################
- name: Install pre-requisite packages
  hosts: localhost
  connection: local
  tasks:
    - name: Install pre-requisite packages
      ansible.builtin.apt:
        pkg:
          - git
          - libsystemd-dev
          - libudev-dev
          - libreadline6-dev
          - pkg-config
          - libxml2-dev
          #- pciutils-dev
          - libboost-all-dev
          - libelf-dev
          - libnl-3-dev
          #- kernel-devel-$(uname -r)
          - build-essential
          - yasm
          - zlib1g-dev
          - libssl-dev
        state: present
        update_cache: true

# Clone example.github.com to /tmp/qat
- name: Build qat
  hosts: localhost
  connection: local
  tasks:
    - name: Clone qat
      ansible.builtin.git:
        repo: https://github.com/intel/qatlib.git
        dest: /tmp/qat
        version: 23.02.0
    - name: Build qat
      shell: ./tmp/qat/autogen.sh #&& source ./configure --enable-service && make -j && make install


